### Valid Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Invalid Signup - invalid email
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "testm",
  "password": "password"
}

### Find user by ID
GET http://localhost:3000/auth/1

### Find all users with given email
GET http://localhost:3000/auth?email=test@test.com

### Delete User by ID 
DELETE http://localhost:3000/auth/1

### Update User
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "testm@test.com",
  "password": "passwordsf"
}